/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.view;

import BLL.LogIn;
import DAL.LogInRepository;
import DAL.ProjectException;
import gui.model.LogInTableModel;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Arber
 */
public class NdrrimiIPaswordit extends javax.swing.JInternalFrame {
    
    LogInRepository dr = new LogInRepository();
    LogInTableModel dtm = new LogInTableModel();
    
    /**
     * Creates new form NdrrimiIPaswordit
     */
    public NdrrimiIPaswordit() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        ndryshoButton = new javax.swing.JButton();
        anuloButton = new javax.swing.JButton();
        passwordiRi1 = new javax.swing.JPasswordField();
        passwordiRi = new javax.swing.JPasswordField();
        passwordiAktual = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "NdryshimiPasswordit", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 24))); // NOI18N
        setClosable(true);

        jLabel2.setText("Passwordi i ri:");

        ndryshoButton.setBackground(new java.awt.Color(102, 255, 102));
        ndryshoButton.setText("Ndrysho");
        ndryshoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ndryshoButtonActionPerformed(evt);
            }
        });

        anuloButton.setBackground(new java.awt.Color(102, 255, 255));
        anuloButton.setText("Anulo");
        anuloButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anuloButtonActionPerformed(evt);
            }
        });

        passwordiRi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordiRi1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Passwordi:");

        jLabel4.setText("Passwordi i ri:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(ndryshoButton)
                        .addGap(47, 47, 47)
                        .addComponent(anuloButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(passwordiAktual, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(passwordiRi, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(passwordiRi1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordiAktual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordiRi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordiRi1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ndryshoButton)
                    .addComponent(anuloButton))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passwordiRi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordiRi1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordiRi1ActionPerformed
    private static LoginDialog ld = LoginDialog.getInstance();
    private void ndryshoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ndryshoButtonActionPerformed
        // TODO add your handling code here:
        if(!(passwordiAktual.getText().equals(ld.login.getPassword()))){
            JOptionPane.showMessageDialog(this, "Nuk e keni shenuar mir passwordin tuaj aktual!!!");
        }
        else if(!(passwordiRi.getText().equals(passwordiRi1.getText()))){
             JOptionPane.showMessageDialog(this, "Passwordi i ri nuk perputhet ne te dy fushat.");
        }else{
            //hajt provo po thu a 
            //spo ban qashtu e provova qka tvyn aj objekti i ri ? sen valla po sbajke qashtu tu munu me zvbulu ujin e vokt
           ld.login.setPassword(passwordiRi1.getText());           
            try {
                dr.edit(ld.login);
                JOptionPane.showMessageDialog(this, "Sukses!");
                

            } catch (ProjectException ex) {
                Logger.getLogger(NdrrimiIPaswordit.class.getName()).log(Level.SEVERE, null, ex);
            }
//qka tka met tjeter veq kalendarin edhe tani mja nreq dizajnin dej tpremten 
           //kqyr qka bana kur e qeli njo psh me ma hek tjetren
           
        }
       
    }//GEN-LAST:event_ndryshoButtonActionPerformed

    private void anuloButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anuloButtonActionPerformed
        // TODO add your handling code here:
        passwordiAktual.setText(null);
            passwordiRi.setText(null);
            passwordiRi1.setText(null);
    }//GEN-LAST:event_anuloButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NdrrimiIPaswordit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NdrrimiIPaswordit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NdrrimiIPaswordit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NdrrimiIPaswordit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NdrrimiIPaswordit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anuloButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton ndryshoButton;
    private javax.swing.JPasswordField passwordiAktual;
    private javax.swing.JPasswordField passwordiRi;
    private javax.swing.JPasswordField passwordiRi1;
    // End of variables declaration//GEN-END:variables
}
